version: 2

models:
  - name: metricas_tweets
    description: "dados de metricas de tweets"
    columns:
      - name: upload_ts
        description: "timestamp of data extraction [partition variable]"
      - name: id
        description: "tweet id [primary key]"
      - name: text
        description: "tweet's text content"
      - name: created_at
        description: "datetime tweet creation"
      - name: retweet_count
        description: "tweet's retweets count"
      - name: reply_count
        description: "tweet's reply count"
      - name: like_count
        description: "tweet's like count"
      - name: quote_count
        description: "number of user profile clicks"
      - name: impression_count
        description: "tweet's impression count"
      - name: user_profile_clicks
        description: "number of clicks in url link"
      - name: url_link_clicks
        description: "time of tweet creation"
      - name: following_count
        description: "user's following count"
      - name: followers_count
        description: "user's followers count at upload day"
      - name: tweet_count
        description: "user's tweets count at upload day"
      - name: listed_count
        description: "user's listed count at upload day"
  - name: twitter_metrics_agg
    description: "dados agregados de métricas de tweets"
    columns:
      - name: upload_day
        description: "day of data extraction [partition variable]"
      - name: retweets
        description: "total day's retweets"
      - name: replies
        description: "total day's replies"
      - name: likes
        description: "total day's likes"
      - name: quote_tweets
        description: "total day's quote tweets"
      - name: impressions
        description: "total day's impressions"
      - name: profile_clicks
        description: "total day's profile clicks"
      - name: links_clicks
        description: "total day's clicks in embeded tweet links"
      - name: followings
        description: "total followings up to upload_day"
      - name: followers
        description: "total followers up to upload_day"
      - name: tweets
        description: "total tweets up to upload_day"
      - name: listed
        description: "total list that BD's account was listed up to upload_day"
  - name: website_user
    description: "dados de acessos ao site da BD"
    columns:
      - name: reference_date
        description: Reference date
      - name: users_1_day
        description: Number of users in 1 day
      - name: users_7_days
        description: Number of users in the last 7 days
      - name: users_14_days
        description: Number of users in the last 14 days
      - name: users_28_days
        description: Number of users in the last 28 days
      - name: users_30_days
        description: Number of users in the last 30 days
      - name: new_users
        description: Number of new users in that date
