default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: basedosdados-dev
      dataset: dbt
      location: US
      threads: 2
<<<<<<< HEAD
      keyfile: /home/laura/.basedosdados/credentials/staging.json
=======
      keyfile: /Users/apple/.basedosdados/credentials/prod.json
>>>>>>> 92b73f7 (fix(schema): fixing tests)
    prod:
      type: bigquery
      method: service-account
      project: basedosdados-dev
      dataset: dbt
      location: US
      threads: 2
<<<<<<< HEAD
      keyfile: /home/laura/.basedosdados/credentials/staging.json
=======
      keyfile: /Users/apple/.basedosdados/credentials/prod.json
>>>>>>> 92b73f7 (fix(schema): fixing tests)
