default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: basedosdados-dev
      dataset: dbt
      location: US
      threads: 2
      keyfile: /Users/lucasmoreira/.basedosdados/credentials/prod.json
    prod:
      type: bigquery
      method: service-account
      project: basedosdados-dev
      dataset: dbt
      location: US
      threads: 2
      keyfile: /Users/lucasmoreira/.basedosdados/credentials/prod.json
