default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: basedosdados-dev
      dataset: dbt
      location: US
      threads: 2
      keyfile: /home/laura/.basedosdados/credentials/staging.json
    prod:
      type: bigquery
      method: service-account
      project: basedosdados-dev
      dataset: dbt
      location: US
      threads: 2
      keyfile: /home/laura/.basedosdados/credentials/staging.json
