version: 2

models:
  - name: available_options_test
    description: "available options da API BD"
    columns:
      - name: elemento
        description: "Elemento Available_options_test"
      - name: chave
        description: "Chave Available_options_test"
      - name: valor
        description: "Valor Available_options_test"