version: 2

models:
  - name: face_quadra
    description: "Valores unitários de terreno das faces de quadra do ano corrente e infraestrutura do trecho de logradouro da face"
    columns:
      - name: ano
        description: Ano
      - name: id_face_quadra
        description: Identificador único de identificação da face de Quadra.
      - name: logradouro.
        description: Nome oficial do logradouro, sendo este definido na legislação municipal.
      - name: geometria
        description: Polígono referente a região de condomínios com sistema de referência de coordenadas SIRGAS 2000 - UTM Zona 24 Sul.
      - name: metrica
        description: O sequencial do trecho do logradouro será preenchido inicialmente com múltiplos de 20 a partir do início do logradouro.
      - name: pavimentacao
        description: Indicar o tipo de pavimentação que reveste a superfície do logradouro.
      - name: agua
        description: Identifica a existência de rede de água ou não no trecho do logradouro.
      - name: esgoto
        description: Identifica a existência de rede de coleta de esgoto cloacal ou não no trecho do logradouro.
      - name: galeria_pluvial
        description: Identifica a existência ou não de rede de drenagem pluvial.
      - name: sarjeta
        description: Identifica a existência ou não de meio-fio.
      - name: iluminacao_publica
        description: Identifica a existência ou não de rede de iluminação pública.
      - name: arborizacao
        description: Identifica a existência ou não de arborização planejada no canteiro central de vias duplas.
      - name: latitude
        description: Refere-se a latitude do ponto da face de quadra cadastrada no sistema do Cadastro Imobiliário Municipal (CIM) de Fortaleza/CE.
      - name: longitude
        description: Refere-se a longitude do ponto da face de quadra cadastrada no sistema do Cadastro Imobiliário Municipal (CIM) de Fortaleza/CE.
      - name: valor
        description: Refere-se ao valor da face de quadra no ano respectivos a publicação dos dados da camada.