version: 2

models:
  - name: br_bd_metadados__prefect_flow_runs
    description: Prefect flow runs info
    tests:
      - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - id
    columns:
      - name: id
        description: Unique identifier for the flow run
        tests:
          - dbt_utils.not_null_proportion:
                at_least: 0.05
      - name: name
        description: Name associated with the specific flow run
        tests:
          - dbt_utils.not_null_proportion:
                at_least: 0.05
      - name: labels
        description: Labels (determines the project the data will be materialized)
        tests:
          - dbt_utils.not_null_proportion:
                at_least: 0.05
      - name: flow_project_name
        description: Name of the project linked to this flow run
        tests:
          - dbt_utils.not_null_proportion:
                at_least: 0.05
      - name: flow_name
        description: Name of the flow linked to this flow run
        tests:
          - dbt_utils.not_null_proportion:
                at_least: 0.05
      - name: flow_archived
        description: Boolean indicating whether the flow run is archived or active
        tests:
          - dbt_utils.not_null_proportion:
                at_least: 0.05
      - name: dataset_id
        description: BigQuery dataset id relevant to this flow run
        tests:
          - dbt_utils.not_null_proportion:
                at_least: 0.05
      - name: table_id
        description: BigQuery table id relevant to this flow run
        tests:
          - dbt_utils.not_null_proportion:
                at_least: 0.05
      - name: start_time
        description: Date and time when the flow run was initiated
        tests:
          - dbt_utils.not_null_proportion:
                at_least: 0.05
      - name: end_time
        description: Date and time when the flow run was completed or ended
        tests:
          - dbt_utils.not_null_proportion:
                at_least: 0.05
      - name: state
        description: Current state of the flow run
        tests:
          - dbt_utils.not_null_proportion:
                at_least: 0.05
      - name: state_message
        description: Additional message or information related to the state/status
            of the flow run
        tests:
          - dbt_utils.not_null_proportion:
                at_least: 0.05
      - name: task_runs
        description: Information or details regarding individual task runs within
            this flow run
        tests:
          - dbt_utils.not_null_proportion:
                at_least: 0.05
      - name: skipped_upload_to_gcs
        description: Boolean indicating whether the upload to GCS (Google Cloud Storage)
            was skipped or not for this flow run.
        tests:
          - dbt_utils.not_null_proportion:
                at_least: 0.05
      - name: error_logs
        description: Error log records
        tests:
          - dbt_utils.not_null_proportion:
                at_least: 0.05
