version: 2

models:
  - name: empresas
    description: Empresas
    columns:
      - name: data
        description: Data
      - name: cnpj_basico
        description: CNPJ Básico
      - name: razao_social
        description: Razão Social
      - name: natureza_juridica
        description: Natureza Jurídica
      - name: qualificacao_responsavel
        description: Qualificação do/a Responsável
      - name: capital_social
        description: Capital Social
      - name: porte
        description: Porte
      - name: ente_federativo
        description: Ente Federativo

  - name: socios
    description: Sócios
    columns:
      - name: data
        description: Data
      - name: cnpj_basico
        description: CNPJ básico
      - name: tipo
        description: Tipo
      - name: nome
        description: Nome
      - name: documento
        description: Documento (CPF mascarado ou CNPJ)
      - name: qualificacao
        description: Qualificação
      - name: data_entrada_sociedade
        description: Data de Entrada na Sociedade
      - name: id_pais
        description: ID País
      - name: cpf_representante_legal
        description: CPF do Representante Legal
      - name: nome_representante_legal
        description: Nome do Representante Legal
      - name: qualificacao_representante_legal
        description: Qualificação do Representante Legal
      - name: faixa_etaria
        description: Faixa Etária

  - name: simples
    description: Simples Nacional
    columns:
      - name: cnpj_basico
        description: CNPJ Básico
      - name: opcao_simples
        description: Opção pelo Simples Nacional
      - name: data_opcao_simples
        description: Data de Opção pelo Simples Nacional
      - name: data_exclusao_simples
        description: Data de Exclusão do Simples Nacional
      - name: opcao_mei
        description: Opção pelo MEI
      - name: data_opcao_mei
        description: Data de Opção pelo MEI
      - name: data_exclusao_mei
        description: Data de Exclusão do MEI

  - name: estabelecimentos
    description: Estabelecimentos
    columns:
      - name: data
        description: Data
      - name: cnpj
        description: CNPJ
      - name: cnpj_basico
        description: CNPJ Básico (8 primeiros dígitos)
      - name: cnpj_ordem
        description: CNPJ Ordem
      - name: cnpj_dv
        description: CNPJ Dígito Verificador
      - name: identificador_matriz_filial
        description: Identificador de Matriz ou Filial
      - name: nome_fantasia
        description: Nome Fantasia
      - name: situacao_cadastral
        description: Situação Cadastral
      - name: data_situacao_cadastral
        description: Data da Situação Cadastral
      - name: motivo_situacao_cadastral
        description: Motivo da Situação Cadastral
      - name: nome_cidade_exterior
        description: Nome da Cidade no Exterior
      - name: id_pais
        description: ID País
      - name: data_inicio_atividade
        description: Data de Início da Atividade
      - name: cnae_fiscal_principal
        description: CNAE Fiscal Principal
      - name: cnae_fiscal_secundaria
        description: CNAEs Fiscais Secundárias
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: id_municipio_rf
        description: ID Município - Receita Federal
      - name: tipo_logradouro
        description: Tipo de Logradouro
      - name: logradouro
        description: Logradouro
      - name: numero
        description: Número
      - name: complemento
        description: Complemento
      - name: bairro
        description: Bairro
      - name: cep
        description: CEP
      - name: ddd_1
        description: DDD 1
      - name: telefone_1
        description: Telefone 1
      - name: ddd_2
        description: DDD 2
      - name: telefone_2
        description: Telefone 2
      - name: ddd_fax
        description: DDD Fax
      - name: fax
        description: Fax
      - name: email
        description: Email
      - name: situacao_especial
        description: Situação Especial
      - name: data_situacao_especial
        description: Data da Situação Especial
