version: 2


models:
  - name: custo_marginal_operacao_semi_horario
      description: #todo 
      columns:
        - name: data
          description: Data de referência da medição
        - name: hora
          description: Hora de referência da medição
        - name: id_subsistema
          description: Identificador do subsitema da usina
        - name: subsistema
          description: Nome do subsistema da usina
        - name: custo_marginal_operacao
          description: Valor do Custo Marginal de Operação (CMO)
    - name: custo_marginal_operacao_semanal
      description: #todo 
      columns:
        - name: data
          description: Data de referência da medição
        - name: hora
          description: Hora de referência da medição
        - name: id_subsistema
          description: Identificador do subsitema da usina
        - name: subsistema
          description: Nome do subsistema da usina
        - name: custo_marginal_operacao_semanal
          description: Valor do Custo Marginal Operacional (CMO) médio semanal
        - name: custo_marginal_operacao_semanal_carga_leve
          description: Valor do Custo Marginal Operacional (CMO) no patamar de carga
              leve
        - name: custo_marginal_operacao_semanal_carga_media
          description: Valor do Custo Marginal Operacional (CMO) no patamar de carga
              média
        - name: custo_marginal_operacao_semanal_carga_pesada
          description: Valor do Custo Marginal Operacional (CMO) no patamar de carga
              pesada
    - name: balanco_energia_subsistemas
      description: #todo 
      columns:
        - name: data
          description: Data de referência da medição
        - name: hora
          description: Hora de referência da medição
        - name: id_subsistema
          description: Identificador do subsitema da usina
        - name: subsistema
          description: Nome do subsistema da usina
        - name: geracao_hidraulica_verificada
          description: Valor verificado de geração hidráulica
        - name: geracao_termica_verificada
          description: Valor verificado de geração térmica
        - name: geracao_eolica_verificada
          description: Valor verificado de geração eólica
        - name: geracao_fotovoltaica_verificada
          description: Valor verificado de geração fotovoltaica
        - name: carga_verificada
          description: Valor verificado da carga
        - name: intercambio_verificado
          description: Valor verificado intercâmbio líquido
    - name: balanco_energia_subsistemas_dessem
      description: #todo 
      columns:
        - name: data
          description: Data de referência da medição
        - name: hora
          description: Hora de referência da medição
        - name: id_subsistema
          description: Identificador do subsitema da usina
        - name: subsistema
          description: Nome do subsistema da usina
        - name: valor_demanda
          description: Valor da demanda do subsistema
        - name: usina_hidraulica_verificada
          description: Valor verificado de geração das usinas hidráulicas
        - name: geracao_pequena_usina_hidraulica_verificada
          description: Valor verificado de geração das pequenas usinas hidráulicas
        - name: geracao_usina_termica_verificada
          description: Valor verificado de geração das usinas térmicas
        - name: geracao_pequena_usina_termica_verificada
          description: Valor verificado de geração das pequenas usinas térmicas
        - name: geracao_eolica_verificada
          description: Valor verificado de geração eólica
        - name: geracao_fotovoltaica_verificada
          description: Valor verificado de geração fotovoltaica