---
models:
  - name: br_inep_enem__dicionario
    description: Dicionário para tradução dos códigos do conjunto br_inep_enem. Para
      taduzir códigos compartilhados entre instituições, como id_municipio, buscar
      por diretórios
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - id_tabela
            - nome_coluna
            - chave
            - cobertura_temporal
      - not_null_proportion_multiple_columns:
          at_least: 0.05
    columns:
      - name: id_tabela
        description: ID Tabela
      - name: nome_coluna
        description: Nome da coluna
      - name: chave
        description: Chave
      - name: cobertura_temporal
        description: Cobertura Temporal
      - name: valor
        description: Valor
  - name: br_inep_enem__microdados
    description: Microdados de notas do ENEM
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [id_inscricao, ano]
      - custom_dictionary_coverage:
          columns_covered_by_dictionary:
            - faixa_etaria
            - sexo
            - estado_civil
            - cor_raca
            - nacionalidade
            - situacao_conclusao
            - tipo_escola
            - ensino
            - dependencia_administrativa_escola
            - localizacao_escola
            - situacao_funcionamento_escola
            - presenca_objetiva
            - tipo_prova_objetiva
            - presenca_ciencias_natureza
            - presenca_ciencias_humanas
            - presenca_linguagens_codigos
            - presenca_matematica
            - tipo_prova_ciencias_natureza
            - tipo_prova_ciencias_humanas
            - tipo_prova_linguagens_codigos
            - tipo_prova_matematica
            - lingua_estrangeira
            - presenca_redacao
          dictionary_model: ref('br_inep_enem__dicionario')
    columns:
      - name: id_inscricao
        description: Número de inscrição no ENEM
      - name: ano
        description: Ano
        tests:
          - relationships:
              to: ref('br_bd_diretorios_data_tempo__ano')
              field: ano.ano
      - name: faixa_etaria
        description: Faixa etária
      - name: sexo
        description: Sexo
      - name: id_municipio_residencia
        description: ID Município da residência - IBGE 7 Dígitos
        tests:
          - custom_relationships:
              to: ref('br_bd_diretorios_brasil__municipio')
              field: id_municipio
              ignore_values:
                - '5200'
                - '3208'
                - '35507'
                - '50308'
                - '4557'
                - '14902'
                - '9502'
                - '24808'
                - '14407'
                - '6200'
                - '5108'
                - '48708'
                - '5109'
                - '18105'
                - '3403'
                - '22505'
                - '13705'
                - '43402'
                - '27408'
                - '1108'
                - '36504'
                - '13700'
                - '2105'
                - '102'
                - '2405'
                - '0'
                - '16602'
                - '8201'
                - '108'
                - '12906'
                - '11606'
      - name: sigla_uf_residencia
        description: Sigla da unidade da federação da residência
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__uf')
              field: sigla
      - name: estado_civil
        description: Estado civil
      - name: cor_raca
        description: Cor ou raça
      - name: nacionalidade
        description: Nacionalidade
      - name: situacao_conclusao
        description: Situação em relação ao ensino médio
      - name: ano_conclusao
        description: Ano de conclusão do ensino médio
      - name: tipo_escola
        description: Tipo de escola do ensino médio
      - name: ensino
        description: Tipo de instituição onde o estudante concluiu ou concluirá o
          ensino médio
      - name: indicador_treineiro
        description: Indica se o inscrito fez a prova com intuito de apenas treinar
          seus conhecimentos
      - name: id_municipio_escola
        description: ID Município da escola em que estudou - IBGE 7 Dígitos
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__municipio')
              field: id_municipio
      - name: sigla_uf_escola
        description: Sigla da unidade da federação da escola em que estudou
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__uf')
              field: sigla
      - name: dependencia_administrativa_escola
        description: Dependência administrativa da escola em que estudou
      - name: localizacao_escola
        description: Localização/zona da escola em que estudou
      - name: situacao_funcionamento_escola
        description: Situação de funcionamento da escola em que estudou
      - name: indicador_certificado
        description: Inscrito solicitará certificação no ensino médio
      - name: nome_certificadora
        description: Nome da entidade certificadora
      - name: sigla_uf_certificadora
        description: Sigla da unidade da federação da entidade certificadora
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__uf')
              field: sigla
      - name: id_municipio_prova
        description: ID Município da cidade da prova - IBGE 7 Dígitos
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__municipio')
              field: id_municipio
      - name: sigla_uf_prova
        description: Sigla da unidade da federação da prova
        tests:
          - relationships:
              to: ref('br_bd_diretorios_brasil__uf')
              field: sigla
      - name: presenca_objetiva
        description: Presença a prova objetiva
      - name: tipo_prova_objetiva
        description: Tipo de prova
      - name: nota_objetiva_competencia_1
        description: Nota da competência 1
      - name: nota_objetiva_competencia_2
        description: Nota da competência 2
      - name: nota_objetiva_competencia_3
        description: Nota da competência 3
      - name: nota_objetiva_competencia_4
        description: Nota da competência 4
      - name: nota_objetiva_competencia_5
        description: Nota da competência 5
      - name: nota_objetiva
        description: Nota da prova objetiva
      - name: respostas_objetiva
        description: Vetor com as respostas da parte objetiva da prova
      - name: gabarito_objetiva
        description: Vetor com o gabarito da parte objetiva da prova
      - name: presenca_ciencias_natureza
        description: Presença à prova objetiva de Ciências da Natureza
      - name: presenca_ciencias_humanas
        description: Presença à prova objetiva de Ciências Humanas
      - name: presenca_linguagens_codigos
        description: Presença à prova objetiva de Linguagens e Códigos
      - name: presenca_matematica
        description: Presença à prova objetiva de Matemática
      - name: tipo_prova_ciencias_natureza
        description: Código do tipo de prova de Ciências da Natureza
      - name: tipo_prova_ciencias_humanas
        description: Código do tipo de prova de Ciências Humanas
      - name: tipo_prova_linguagens_codigos
        description: Código do tipo de prova de Linguagens e Códigos
      - name: tipo_prova_matematica
        description: Código do tipo de prova de Matemática
      - name: nota_ciencias_natureza
        description: Nota da prova de Ciências da Natureza
      - name: nota_ciencias_humanas
        description: Nota da prova de Ciências Humanas
      - name: nota_linguagens_codigos
        description: Nota da prova de Linguagens e Códigos
      - name: nota_matematica
        description: Nota da prova de Matemática
      - name: respostas_ciencias_natureza
        description: Vetor com as respostas da parte objetiva da prova de Ciências
          da Natureza
      - name: respostas_ciencias_humanas
        description: Vetor com as respostas da parte objetiva da prova de Ciências
          Humanas
      - name: respostas_linguagens_codigos
        description: Vetor com as respostas da parte objetiva da prova de Linguagens
          e Códigos
      - name: respostas_matematica
        description: Vetor com as respostas da parte objetiva da prova de Matemática
      - name: gabarito_ciencias_natureza
        description: 'Vetor com o gabarito da parte objetiva da prova  de Ciências
          da Natureza (Obs.: as 45 primeiras posições deste campo são referentes ao
          respectivo gabarito)'
      - name: gabarito_ciencias_humanas
        description: 'Vetor com o gabarito da parte objetiva da prova  de Ciências
          Humanas (Obs.: as 45 primeiras posições deste campo são referentes ao respectivo
          gabarito)'
      - name: gabarito_linguagens_codigos
        description: 'Vetor com o gabarito da parte objetiva da prova  de Linguagens
          e Códigos (Obs.: as 45 primeiras posições deste campo são referentes ao
          respectivo gabarito)'
      - name: gabarito_matematica
        description: 'Vetor com o gabarito da parte objetiva da prova  de Matemática
          (Obs.: as 45 primeiras posições deste campo são referentes ao respectivo
          gabarito)'
      - name: lingua_estrangeira
        description: Língua Estrangeira
      - name: presenca_redacao
        description: Presença à redação
      - name: nota_redacao_competencia_1
        description: Nota da competência 1
      - name: nota_redacao_competencia_2
        description: Nota da competência 2
      - name: nota_redacao_competencia_3
        description: Nota da competência 3
      - name: nota_redacao_competencia_4
        description: Nota da competência 4
      - name: nota_redacao_competencia_5
        description: Nota da competência 5
      - name: nota_redacao
        description: Nota da prova de redação
      - name: indicador_questionario_socioeconomico
        description: Respondeu o Questionário Socioeconômico
  - name: br_inep_enem__questionario_socioeconomico_2023
    description: Respostas do questionário socioeconômico de 2023.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [id_inscricao]
      - custom_dictionary_coverage:
          columns_covered_by_dictionary:
            - q001
            - q002
            - q003
            - q004
            - q005
            - q006
            - q007
            - q008
            - q009
            - q010
            - q011
            - q012
            - q013
            - q014
            - q015
            - q016
            - q017
            - q018
            - q019
            - q020
            - q021
            - q022
            - q023
            - q024
            - q025
          dictionary_model: ref('br_inep_enem__dicionario')
    columns:
      - name: id_inscricao
        description: Número de inscrição no ENEM
      - name: q001
        description: Até que série seu pai, ou o homem responsável por você, estudou?
      - name: q002
        description: Até que série sua mãe, ou a mulher responsável por você, estudou?
      - name: q003
        description: A partir da apresentação de algumas ocupações divididas em grupos
          ordenados, indique o grupo que contempla a ocupação mais próxima da ocupação
          do seu pai ou do homem responsável por você. (Se ele não estiver trabalhando,
          escolha uma ocupação pensando no último trabalho dele).
      - name: q004
        description: A partir da apresentação de algumas ocupações divididas em grupos
          ordenados, indique o grupo que contempla a ocupação mais próxima da ocupação
          da sua mãe ou da mulher responsável por você. (Se ela não estiver trabalhando,
          escolha uma ocupação pensando no último trabalho dela).
      - name: q005
        description: Incluindo você, quantas pessoas moram atualmente em sua residência?
      - name: q006
        description: Qual é a renda mensal de sua família? (Some a sua renda com a
          dos seus familiares.)
      - name: q007
        description: Em sua residência trabalha empregado(a) doméstico(a)?
      - name: q008
        description: Na sua residência tem banheiro?
      - name: q009
        description: Na sua residência tem quartos para dormir?
      - name: q010
        description: Na sua residência tem carro?
      - name: q011
        description: Na sua residência tem motocicleta?
      - name: q012
        description: Na sua residência tem geladeira?
      - name: q013
        description: Na sua residência tem freezer (independente ou segunda porta
          da geladeira)?
      - name: q014
        description: Na sua residência tem máquina de lavar roupa? (o tanquinho NÃO
          deve ser considerado)
      - name: q015
        description: Na sua residência tem máquina de secar roupa (independente ou
          em conjunto com a máquina de lavar roupa)?
      - name: q016
        description: Na sua residência tem forno micro-ondas?
      - name: q017
        description: Na sua residência tem máquina de lavar louça?
      - name: q018
        description: Na sua residência tem aspirador de pó?
      - name: q019
        description: Na sua residência tem televisão em cores?
      - name: q020
        description: Na sua residência tem aparelho de DVD?
      - name: q021
        description: Na sua residência tem TV por assinatura?
      - name: q022
        description: Na sua residência tem telefone celular?
      - name: q023
        description: Na sua residência tem telefone fixo?
      - name: q024
        description: Na sua residência tem computador?
      - name: q025
        description: Na sua residência tem acesso à Internet?
