version: 2

models:
  - name: microdados
    description: dbt model for table microdados
    columns:
      - name: ano
        description: Ano
      - name: mes
        description: Mês
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: cnpj
        description: Cadastro Nacional de Pessoa Jurídica
      - name: empresa
        description: Nome da empresa
      - name: porte_empresa
        description: Porte da empresa
      - name: tecnologia
        description: Tecnologia
      - name: transmissao
        description: Meios de transmissão
      - name: velocidade
        description: Velocidade contratada
      - name: acessos
        description: Número total de contratos
  - name: densidade_brasil
    description: dbt model for table densidade_brasil
    columns:
      - name: ano
        description: Ano
      - name: mes
        description: Mês
      - name: acessos
        description: Total de acessos
      - name: densidade
        description: Densidade de acessos por 100 domicílios
  - name: densidade_uf
    description: dbt model for table densidade_uf
    columns:
      - name: ano
        description: Ano
      - name: mes
        description: Mês
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: acessos
        description: Total de acessos
      - name: densidade
        description: Densidade de acessos por 100 domicílios
  - name: densidade_municipio
    description: dbt model for table densidade_municipio
    columns:
      - name: ano
        description: Ano
      - name: mes
        description: Mês
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: id_municipio
        - description: ID Município - IBGE 7 Dígitos
      - name: acessos
        description: Total de acessos
      - name: densidade
        description: Densidade de acessos por 100 domicílios