---
version: 2
models:
  - name: world_ampas_oscar__winner_demographics
    description: The table presents demographic information of Oscar winners across
      various categories, including Best Director, Best Actor, Best Supporting Actor,
      Best Actress, and Best Supporting Actress. The data spans from the 1927 edition
      to the 2014 edition of the Oscars, providing insights into the winners' demographics
      over time.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [name, category, year_edition]
    columns:
      - name: name
        description: Winner name
        tests: [not_null]
      - name: birth_year
        description: Year of birth
        tests:
          - relationships:
              to: ref('br_bd_diretorios_data_tempo__ano')
              field: ano.ano   
      - name: birth_date
        description: Date of birth
        tests:
          - relationships:
              to: ref('br_bd_diretorios_data_tempo__data')
              field: data.data
      - name: birthplace
        description: Birthplace
      - name: race_ethnicity
        description: Race ethnicity
      - name: religion
        description: Religion
      - name: sexual_orientation
        description: Sexual orientation
      - name: year_edition
        description: Year of the award edition
      - name: category
        description: Award category
        tests: [not_null]
      - name: movie
        description: Movie
