version: 2

models:
  - name: br_tse_eleicoes__candidatos
    description: "microdados de candidatos"
    columns:
      - name: ano
        description: Ano
      - name: tipo_eleicao
        description: Tipo da Eleição
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos 
      - name: id_municipio_tse
        description: ID Município - Tribunal Superior Eleitoral (TSE)
      - name: id_candidato_bd
        description: ID Candidato no Banco de Dados
      - name: cpf
        description: CPF
      - name: titulo_eleitoral
        description: Título Eleitoral
      - name: sequencial
        description: Sequencial
      - name: numero
        description: Número
      - name: nome
        description: Nome
      - name: nome_urna
        description: Nome Urna
      - name: numero_partido
        description: Número do Partido
      - name: sigla_partido
        description: Sigla do Partido
      - name: cargo
        description: Cargo
      - name: situacao
        description: Situação
      - name: ocupacao
        description: Ocupação
      - name: data_nascimento
        description: Data de Nascimento
      - name: idade
        description: Idade
      - name: genero
        description: Gênero
      - name: instrucao
        description: Instrução
      - name: estado_civil
        description: Estado Civil
      - name: nacionalidade
        description: Nacionalidade
      - name: sigla_uf_nascimento
        description: Sigla da UF de Nascimento
      - name: municipio_nascimento
        description: Município de Nascimento
      - name: email
        description: E-mail
      - name: raca
        description: Raça ou cor
      - name: situacao_totalizacao
        description: Situação Totalização
      - name: numero_federacao
        description: Número Federação
      - name: nome_federacao
        description: Nome Federação
      - name: sigla_federacao
        description: Sigla Federação
      - name: composicao_federacao
        description: Composição Federação
      - name: prestou_contas
        description: Indicador de prestação de contas
  - name: br_tse_eleicoes__bens_candidato
    description: "microdados bens candidato"
    columns:
      - name: ano
        description: Ano
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: tipo_eleicao
        description: Tipo da Eleição
      - name: sequencial_candidato
        description: Sequencial do Candidato
      - name: id_candidato_bd
        description: ID Candidato - Base dos Dados
      - name: id_tipo_item
        description: ID Tipo Item
      - name: tipo_item
        description: Tipo Item
      - name: descricao_item
        description: Descrição do Item
      - name: valor_item
        description: Valor do Item (R$)
  - name: br_tse_eleicoes__receitas_candidato
    description: microdados receitas candidato
    columns:
      - name: ano
        description: Ano
      - name: turno
        description: Turno
      - name: tipo_eleicao
        description: Tipo da Eleição
      - name: sigla_uf
        description: Sigla da Unidade da Federação
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: id_municipio_tse
        description: ID Município - TSE
      - name: numero_candidato
        description: Número do Candidato
      - name: cpf_candidato
        description: CPF do Candidato
      - name: cnpj_candidato
        description: CNPJ do Candidato
      - name: titulo_eleitor_candidato
        description: Título Eleitoral do Candidato
      - name: sequencial_candidato
        description: Sequencial do Candidato
      - name: id_candidato_bd
        description: ID Candidato - Base dos Dados
      - name: nome_candidato
        description: Nome do Candidato
      - name: cpf_vice_suplente
        description: CPF do Vice Suplente
      - name: numero_partido
        description: Número do Partido
      - name: nome_partido
        description: Nome do Partido
      - name: sigla_partido
        description: Sigla do Partido
      - name: cargo
        description: Cargo
      - name: sequencial_receita
        description: Sequencial da Receita
      - name: data_receita
        description: Data da Receita
      - name: fonte_receita
        description: Fonte da Receita
      - name: origem_receita
        description: Origem da Receita
      - name: natureza_receita
        description: Natureza da Receita
      - name: especie_receita
        description: Espécie da Receita
      - name: situacao_receita
        description: Situação da Receita
      - name: descricao_receita
        description: Descrição da Receita
      - name: valor_receita
        description: Valor da Receita (R$)
      - name: sequencial_candidato_doador
        description: Sequencial do Candidato Doador
      - name: cpf_cnpj_doador
        description: CPF/CNPJ do Doador
      - name: sigla_uf_doador
        description: Sigla da UF do Doador
      - name: id_municipio_tse_doador
        description: ID Município - TSE do Doador
      - name: nome_doador
        description: Nome do Doador
      - name: nome_doador_rf
        description: Nome do Doador - RF
      - name: cargo_candidato_doador
        description: Cargo do Candidato Doador
      - name: numero_partido_doador
        description: Número do Partido do Doador
      - name: sigla_partido_doador
        description: Sigla do Partido do Doador
      - name: nome_partido_doador
        description: Nome do Partido do Doador
      - name: esfera_partidaria_doador
        description: Esfera Partidária do Doador
      - name: numero_candidato_doador
        description: Número do Candidato do Doador
      - name: cnae_2_doador
        description: CNAE 2 do Doador
      - name: descricao_cnae_2_doador
        description: Descrição da Classificação Nacional de Atividades Econômicas 2.0 do doador
      - name: cpf_cnpj_doador_orig
        description: CPF ou CNPJ do doador originário
      - name: nome_doador_orig
        description: Nome do doador originário
      - name: nome_doador_orig_rf
        description: Nome do doador originário - Receita Federal
      - name: tipo_doador_orig
        description: Tipo do doador originário
      - name: descricao_cnae_2_doador_orig
        description: Descrição da Classificação Nacional de Atividades Econômicas 2.0 do doador originário
      - name: nome_administrador
        description: Nome do administrador
      - name: cpf_administrador
        description: CPF do administrador
      - name: numero_recibo_eleitoral
        description: Número do recibo eleitoral
      - name: numero_documento
        description: Número do documento
      - name: numero_recibo_doacao
        description: Número do recibo da doação
      - name: numero_documento_doacao
        description: Número do documento da doação
      - name: tipo_prestacao_contas
        description: Tipo de prestação de contas
      - name: data_prestacao_contas
        description: Data de prestação de contas
      - name: sequencial_prestador_contas
        description: Sequencial do prestador de contas
      - name: cnpj_prestador_contas
        description: CNPJ do prestador de contas
      - name: entrega_conjunto
        description: Entrega em conjunto
  - name: br_tse_eleicoes__despesas_candidato
    description: microdados despesas candidato
    columns:
      - name: ano
        description: Ano
      - name: turno
        description: Turno
      - name: tipo_eleicao
        description: Tipo da eleição
      - name: sigla_uf
        description: Sigla da unidade da federação
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: id_municipio_tse
        description: ID Município - TSE
      - name: numero_candidato
        description: Número do candidato
      - name: cpf_candidato
        description: CPF do candidato
      - name: sequencial_candidato
        description: Sequencial do candidato
      - name: id_candidato_bd
        description: ID Candidato - Base dos Dados
      - name: nome_candidato
        description: Nome do candidato
      - name: cpf_vice_suplente
        description: CPF do vice ou suplente
      - name: numero_partido
        description: Número do partido
      - name: sigla_partido
        description: Sigla do partido
      - name: nome_partido
        description: Nome do partido
      - name: cargo
        description: Cargo
      - name: sequencial_despesa
        description: Sequencial da despesa
      - name: data_despesa
        description: Data da despesa
      - name: tipo_despesa
        description: Tipo da despesa
      - name: descricao_despesa
        description: Descrição da despesa
      - name: origem_despesa
        description: Origem da despesa
      - name: valor_despesa
        description: Valor da despesa
      - name: tipo_prestacao_contas
        description: Tipo de prestação de contas
      - name: data_prestacao_contas
        description: Data de prestação de contas
      - name: sequencial_prestador_contas
        description: Sequencial do prestador de contas
      - name: cnpj_prestador_contas
        description: CNPJ do prestador de contas
      - name: cnpj_candidato
        description: CNPJ do candidato
      - name: tipo_documento
        description: Tipo do documento
      - name: numero_documento
        description: Número do documento
      - name: especie_recurso
        description: Espécie do recurso
      - name: fonte_recurso
        description: Fonte do recurso
      - name: cpf_cnpj_fornecedor
        description: CPF ou CNPJ do fornecedor
      - name: nome_fornecedor
        description: Nome do fornecedor
      - name: nome_fornecedor_rf
        description: Nome do fornecedor - Receita Federal
      - name: cnae_2_fornecedor
        description: Classificação Nacional de Atividades Econômicas 2.0 do fornecedor
      - name: descricao_cnae_2_fornecedor
        description: Descrição da Classificação Nacional de Atividades Econômicas 2.0 do fornecedor
      - name: tipo_fornecedor
        description: Tipo do fornecedor
      - name: esfera_partidaria_fornecedor
        description: Esfera partidária do fornecedor
      - name: sigla_uf_fornecedor
        description: Sigla da unidade da federação do fornecedor
      - name: id_municipio_tse_fornecedor
        description: ID Município do fornecedor - TSE
      - name: sequencial_candidato_fornecedor
        description: Sequencial do candidato fornecedor
      - name: numero_candidato_fornecedor
        description: Número do candidato do fornecedor
      - name: numero_partido_fornecedor
        description: Número do partido do fornecedor
      - name: sigla_partido_fornecedor
        description: Sigla do partido do fornecedor
      - name: nome_partido_fornecedor
        description: Nome do partido do fornecedor
      - name: cargo_fornecedor
        description: Cargo do fornecedor
  - name: br_tse_eleicoes__receitas_comite
    description: Receitas de comitês eleitorais
    columns:
      - name: ano
        description: Ano
      - name: tipo_eleicao
        description: Tipo da eleição
      - name: sigla_uf
        description: Sigla da unidade da federação
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: id_municipio_tse
        description: ID Município - TSE
      - name: tipo_comite
        description: Tipo do comite
      - name: sequencial_comite
        description: Sequencial do comite
      - name: numero_partido
        description: Número do partido
      - name: sigla_partido
        description: Sigla do partido
      - name: data_receita
        description: Data da receita
      - name: valor_receita
        description: Valor da receita
      - name: origem_receita
        description: Origem da receita
      - name: fonte_receita
        description: Fonte da receita
      - name: natureza_receita
        description: Natureza da receita
      - name: situacao_receita
        description: Situação da receita
      - name: descricao_receita
        description: Descrição da receita
      - name: tipo_documento
        description: Tipo de documento
      - name: numero_documento
        description: Número do documento
      - name: nome_membro
        description: Nome do membro
      - name: cpf_membro
        description: CPF do membro
      - name: cnpj_prestador_contas
        description: CNPJ do prestador de contas
      - name: cpf_cnpj_doador
        description: CPF ou CNPJ do doador
      - name: sigla_uf_doador
        description: Sigla da unidade da federação do doador
      - name: nome_doador
        description: Nome do doador
      - name: nome_doador_rf
        description: Nome do doador - Receita Federal
      - name: descricao_cnae_2_doador
        description: Descrição da Classificação Nacional de Atividades Econômicas 2.0 do doador
      - name: numero_partido_doador
        description: Número do partido do doador
      - name: numero_candidato_doador
        description: Número do Candidato do Doador
      - name: cnae_2_doador
        description: CNAE 2 do Doador
      - name: cpf_cnpj_doador_orig
        description: CPF ou CNPJ do doador originário
      - name: nome_doador_orig
        description: Nome do doador originário
      - name: tipo_doador_orig
        description: Tipo do doador originário
      - name: descricao_cnae_2_doador_orig
        description: Descrição da Classificação Nacional de Atividades Econômicas 2.0 do doador originário
      - name: nome_doador_orig_rf
        description: Nome do doador originário - Receita Federal
  - name: br_tse_eleicoes__receitas_orgao_partidario
    description: Receitas de comitês eleitorais
    columns:
      - name: ano
        description: Ano
      - name: sigla_uf
        description: Sigla da unidade da federação
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: id_municipio_tse
        description: ID Município - Tribunal Superior Eleitoral (TSE)
      - name: tipo_eleicao
        description: Tipo da eleição
      - name: esfera_partidaria
        description: Esfera Partidária
      - name: sigla_uf_diretorio
        description: Sigla UF do diretório
      - name: id_municipio_diretorio
        description: ID Município IBGE 7 Dígitos do diretório
      - name: id_municipio_tse_diretorio
        description: ID Municipio TSE do diretório
      - name: tipo_diretorio
        description: Tipo diretório
      - name: sequencial_diretorio
        description: Sequencial do diretório
      - name: numero_partido
        description: Número do partido
      - name: sigla_partido
        description: Sigla do partido
      - name: nome_partido
        description: Nome do partido
      - name: numero_recibo_eleitoral
        description: Número do recibo eleitoral
      - name: tipo_documento
        description: Tipo do documento
      - name: numero_documento
        description: Número do documento
      - name: tipo_prestacao_contas
        description: Tipo de prestação de contas
      - name: data_prestacao_contas
        description: Data de prestação de contas
      - name: sequencial_prestador_contas
        description: Sequencial do prestador de contas
      - name: cnpj_prestador_contas
        description: CNPJ do prestador de contas
      - name: data_receita
        description: Data da receita
      - name: valor_receita
        description: Valor da receita
      - name: origem_receita
        description: Origem da receita
      - name: fonte_receita
        description: Fonte da receita
      - name: natureza_receita
        description: Natureza da receita
      - name: especie_receita
        description: Espécie da receita
      - name: descricao_receita
        description: Descrição da receita
      - name: sequencial_receita
        description: Sequencial da receita
      - name: cnae_2_doador
        description: Classificação Nacional de Atividades Econômicas 2.0 do doador
      - name: descricao_cnae_2_doador
        description: Descrição da Classificação Nacional de Atividades Econômicas 2.0 do doador
      - name: cpf_cnpj_doador
        description: CPF ou CNPJ do doador
      - name: nome_doador
        description: Nome do doador
      - name: nome_doador_rf
        description: Nome do doador - Receita Federal
      - name: esfera_partidaria_doador
        description: Esfera partidária do doador
      - name: sigla_uf_doador
        description: Sigla da unidade da federação do doador
      - name: id_municipio_doador
        description: ID Município do doador - IBGE
      - name: id_municipio_tse_doador
        description: ID Município do doador - TSE
      - name: sequencial_candidato_doador
        description: Sequencial do candidato doador
      - name: numero_candidato_doador
        description: Número do candidato doador
      - name: cargo_candidato_doador
        description: Cargo do candidato doador
      - name: numero_partido_doador
        description: Número do partido do doador
      - name: sigla_partido_doador
        description: Sigla do partido do doador
      - name: nome_partido_doador
        description: Nome do partido do doador
      - name: numero_recibo_doacao
        description: Número do recibo da doação
      - name: numero_documento_doacao
        description: Número do documento da doação
      - name: cpf_cnpj_doador_orig
        description: CPF ou CNPJ do doador originário
      - name: nome_doador_orig
        description: Nome do doador originário
      - name: tipo_doador_orig
        description: Tipo do doador originário
      - name: descricao_cnae_2_doador_orig
        description: Descrição da Classificação Nacional de Atividades Econômicas 2.0 do doador originário
      - name: nome_doador_orig_rf
        description: Nome do doador originário - Receita Federal
  - name: br_tse_eleicoes__resultados_candidato
    description: Resultados a nível de candidato.
    columns:
      - name: ano
        description: Ano
      - name: turno
        description: Turno
      - name: tipo_eleicao
        description: Tipo da eleição
      - name: sigla_uf
        description: Sigla da unidade da federação
      - name: id_municipio
        description: ID Município - IBGE 7 Dígitos
      - name: id_municipio_tse
        description: ID Município - TSE
      - name: cargo
        description: Cargo
      - name: numero_partido
        description: Número do partido
      - name: sigla_partido
        description: Sigla do partido
      - name: numero_candidato
        description: Número do candidato
      - name: sequncial_candidato
        description: Sequencial do candidato
      - name: id_candidato_bd
        description: ID Candidato - Base dos Dados
      - name: nome_candidato
        description: Nome do candidato
      - name: resultado
        description: Resultado
      - name: votos
        description: Número de votos