---
version: 2
models:
  - name: microdados
    description: Microdados de pesquisas eleitorais
    tests:
      - not_null_proportion_multiple_columns:
          at_least: 0.41
    columns:
      - name: id_pesquisa
        description: ID da pesquisa
        tests: [not_null]
      - name: ano
        description: Ano
        tests:
          - relationships:
              to: ref('br_bd_diretorios_data_tempo__ano')
              field: ref('ano.ano')
      - name: sigla_uf
        description: Sigla da Unidade da Federação
        tests:
          - custom_relationships:
              to: ref('br_bd_diretorios_brasil__uf')
              field: sigla
              ignore_values: [RE]
              proportion_allowed_failures: 0.2
      - name: nome_municipio
        description: Nome do município
      - name: cargo
        description: Cargo
      - name: data
        description: Data
        tests:
          - relationships:
              to: ref('br_bd_diretorios_data_tempo__data')
              field: data.data
      - name: data_referencia
        description: Data de referência
      - name: instituto
        description: Instituto realizador
      - name: contratante
        description: Contratante
      - name: orgao_registro
        description: Orgão de registro
      - name: numero_registro
        description: Número de registro
      - name: quantidade_entrevistas
        description: Quantidade de entrevistas
      - name: margem_mais
        description: Margem a mais
      - name: margem_menos
        description: Margem a menos
      - name: tipo
        description: Tipo
      - name: turno
        description: Turno
      - name: tipo_voto
        description: Tipo do voto
        tests: [not_null]
      - name: id_cenario
        description: ID do cenário
        tests: [not_null]
      - name: descricao_cenario
        description: Descrição do cenário
        tests: [not_null]
      - name: id_candidato_poder360
        description: ID do candidato - Poder360
        tests: [not_null]
      - name: nome_candidato
        description: Nome do candidato
        tests: [not_null]
      - name: sigla_partido
        description: Sigla do partido
        tests: [not_null]
      - name: condicao
        description: Condição
        tests: [not_null]
      - name: percentual
        description: Percentual
        tests: [not_null]
