name: Deploy Elementary Report
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]  
  workflow_dispatch:
jobs:
  elementary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dbt project
        uses: actions/checkout@v3
      - name: Listar Diretórios
        run: |
          pwd   
      - name: Listar Árvore de Arquivos
        run: |
          tree               
      - name: Run Elementary
        uses: elementary-data/run-elementary-action@v1.11
        with:
          project-dir: "/home/runner/work/queries-basedosdados-dev/queries-basedosdados-dev/"
          #profile-target: "dev"
          warehouse-type: bigquery 
          adapter-version: 1.5.6 
          profiles-yml: ${{ secrets.ELEMENTARY_PROFILES_YML }} 
          edr-command:
            edr report
              --file-path "report.html"
            &&
            edr send-report
              --google-service-account-path "/tmp/gcs_keyfile.json"
              --gcs-bucket-name "${{ secrets.GCS_BUCKET_NAME }}"
              --update-bucket-website "true"
          bigquery-keyfile: ${{ secrets.BIGQUERY_KEYFILE }}
          gcs-keyfile: ${{ secrets.GCS_KEYFILE }} 
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: report.html
          path: report.html
      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: edr.log
          path: edr.log
