---
name: Metadata Automation
on:
  push:
    branches: ['*']
jobs:
  update-metadata:
    name: Update metadata from Google Sheets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Import Secrets
        id: import_secrets
        uses: hashicorp/vault-action@v2.4.1
        with:
          url: https://vault.basedosdados.org
          token: ${{ secrets.VAULT_TOKEN}}
          secrets: |
            secret/data/queries_credentials/basedosdados-dev    GCP_SA_KEY_BASE64 | GCP_SA_KEY_BASE64;
      - name: Set up poetry
        run: pipx install poetry==1.8.5
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: poetry
          python-version: '3.9'
      - name: Checkout to the head ref
        run: |-
          git fetch --depth=1
          git checkout ${{ github.head_ref }}
      - name: Update metadata
        env:
          GCP_SA_KEY_BASE64: ${{ steps.import_secrets.outputs.GCP_SA_KEY_BASE64 }}
        run: |-
          poetry run python .github/workflows/scripts/metadata_automation.py
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update metadata
